[package]
name = "lihkg"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1"
lazy_static = "1.4.0"
rand = "0.8.5"
plotters = "0.3.4"
rayon = "1.7.0"
dashmap = { version = "5.4.0", features = ["rayon"] }
